spring:
  application:
    name: courts-service
  profiles:
    active: default
  cloud:
    config:
      url: http://localhost:8071
      enabled: true
  config:
    import: "configserver:"

management:
  endpoints:
    web:
      exposure:
        include: health, info, refresh, mappings
    enabled-by-default: true